const QUOTES = [
  { text: "El caos es un orden aún no descifrado.", author: "José Saramago" },
  { text: "Que la Fuerza te acompañe.", author: "Star Wars" },
  { text: "No hay atajos para ningún lugar al que valga la pena ir.", author: "Beverly Sills" },
  { text: "Hablar es barato. Muéstrame el código.", author: "Linus Torvalds" },
  { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
  { text: "Camina hacia donde te lleve el sable, sin miedo.", author: "Yoda" },
  { text: "Cualquier tecnología suficientemente avanzada es indistinguible de la magia.", author: "Arthur C. Clarke" },
  { text: "El futuro ya está aquí, solo que no está distribuido de manera uniforme.", author: "William Gibson" },
  { text: "Primero resuelve el problema, luego escribe el código.", author: "John Johnson" },
  { text: "La mejor forma de predecir el futuro es inventarlo.", author: "Alan Kay" },
  { text: "El conocimiento se comparte, no se acumula.", author: "Anónimo" },
  { text: "No temas a la perfección, nunca la alcanzarás.", author: "Salvador Dalí" },
  { text: "Todo lo que no te mata, te fortalece.", author: "Friedrich Nietzsche" },
  { text: "Un viaje de mil millas comienza con un solo paso.", author: "Lao Tzu" },
  { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
  { text: "Somos lo que hacemos repetidamente. La excelencia no es un acto, es un hábito.", author: "Aristóteles" },
  { text: "El código limpio siempre parece haber sido escrito por alguien a quien le importa.", author: "Robert C. Martin" },
  { text: "No hay que temer a los robots, hay que temer a los humanos.", author: "Isaac Asimov" },
  { text: "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre.", author: "Mahatma Gandhi" },
  { text: "Solo sé que no sé nada.", author: "Sócrates" },
  { text: "Pienso, luego existo.", author: "René Descartes" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
  { text: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
  { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
  { text: "La lógica te llevará de A a B. La imaginación te llevará a todas partes.", author: "Albert Einstein" },
  { text: "Un experto es alguien que ha cometido todos los errores posibles en un campo muy reducido.", author: "Niels Bohr" },
  { text: "La ciencia es una forma de pensar mucho más que un cuerpo de conocimientos.", author: "Carl Sagan" },
  { text: "En algún lugar, algo increíble está esperando ser descubierto.", author: "Carl Sagan" },
  { text: "Somos polvo de estrellas contemplando estrellas.", author: "Carl Sagan" },
  { text: "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", author: "Marcel Proust" },
  { text: "No es la especie más fuerte la que sobrevive, sino la que mejor se adapta al cambio.", author: "Charles Darwin" },
  { text: "La persistencia es el camino del éxito.", author: "Charlie Chaplin" },
  { text: "Si buscas resultados distintos, no hagas siempre lo mismo.", author: "Albert Einstein" },
  { text: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.", author: "Henry Ford" },
  { text: "La calidad no es un acto, es un hábito.", author: "Aristóteles" },
  { text: "Hazlo simple, pero significativo.", author: "Don Draper" },
  { text: "El diseño no es solo apariencia. El diseño es cómo funciona.", author: "Steve Jobs" },
  { text: "Innovar es decir no a mil cosas.", author: "Steve Jobs" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein" },
  { text: "No hay viento favorable para el que no sabe a dónde va.", author: "Séneca" },
  { text: "La suerte es lo que ocurre cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
  { text: "Nada es imposible, la palabra misma lo dice: 'yo soy posible'.", author: "Audrey Hepburn" },
  { text: "El que no arriesga, no gana.", author: "Anónimo" },
  { text: "Hazte fuerte para las tormentas de la vida, no para evitar la lluvia.", author: "Anónimo" },
  { text: "El tiempo que disfrutas perdiendo no es tiempo perdido.", author: "John Lennon" },
  { text: "La mente que se abre a una nueva idea jamás vuelve a su tamaño original.", author: "Albert Einstein" },
  { text: "No importa lo lento que vayas, siempre y cuando no te detengas.", author: "Confucio" },
  { text: "El hombre que mueve una montaña comienza cargando pequeñas piedras.", author: "Confucio" },
  { text: "Elige un trabajo que ames y no tendrás que trabajar ni un día de tu vida.", author: "Confucio" },
  { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
  { text: "Conócete a ti mismo.", author: "Inscripción en el templo de Delfos" },
  { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
  { text: "Todo parece imposible hasta que se hace.", author: "Nelson Mandela" },
  { text: "El valor no es la ausencia del miedo, sino el triunfo sobre él.", author: "Nelson Mandela" },
  { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
  { text: "Primero te ignoran, luego se ríen de ti, luego te atacan, luego ganas.", author: "Mahatma Gandhi" },
  { text: "La grandeza no está en nunca caer, sino en levantarse cada vez que caemos.", author: "Confucio" },
  { text: "No dejes que el ruido de las opiniones ajenas silencie tu propia voz interior.", author: "Steve Jobs" },
  { text: "Vive de tal manera que si alguien habla mal de ti, nadie lo crea.", author: "Anónimo" },
  { text: "Un barco está seguro en el puerto, pero no es para eso que fue construido.", author: "William Shedd" },
  { text: "La vida es como montar en bicicleta, para mantener el equilibrio hay que seguir moviéndose.", author: "Albert Einstein" },
  { text: "Si no puedes volar, corre. Si no puedes correr, camina. Pero sigue avanzando.", author: "Martin Luther King Jr." },
  { text: "Tengo un sueño.", author: "Martin Luther King Jr." },
  { text: "La oscuridad no puede echar fuera la oscuridad, solo la luz puede hacerlo.", author: "Martin Luther King Jr." },
  { text: "Sé tú mismo, todos los demás ya están ocupados.", author: "Oscar Wilde" },
  { text: "El pesimista se queja del viento, el optimista espera que cambie.", author: "William Arthur Ward" },
  { text: "La única forma de hacer un buen trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "No se trata de tener tiempo, se trata de hacer tiempo.", author: "Anónimo" },
  { text: "La disciplina es el puente entre las metas y los logros.", author: "Jim Rohn" },
  { text: "Cae siete veces, levántate ocho.", author: "Proverbio japonés" },
  { text: "El que no arriesga un huevo, no tiene un pollo.", author: "Proverbio popular" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
  { text: "El hombre es la medida de todas las cosas.", author: "Protágoras" },
  { text: "Nada ocurre hasta que algo se mueve.", author: "Albert Einstein" },
  { text: "La fantasía es más importante que el conocimiento, porque el conocimiento es limitado.", author: "Albert Einstein" },
  { text: "El aprendizaje nunca agota la mente.", author: "Leonardo da Vinci" },
  { text: "La pintura es poesía muda, la poesía es pintura ciega.", author: "Leonardo da Vinci" },
  { text: "Quien no castiga el mal, ordena que se haga.", author: "Leonardo da Vinci" },
  { text: "El movimiento es vida.", author: "Leonardo da Vinci" },
  { text: "Hay más riqueza en el mundo interior que en el exterior.", author: "Anónimo" },
  { text: "Un día sin risa es un día perdido.", author: "Charlie Chaplin" },
  { text: "Mirando de cerca la vida es una tragedia, pero de lejos es una comedia.", author: "Charlie Chaplin" },
  { text: "El programador de mayor éxito es aquel que sabe cuándo dejar de programar.", author: "Anónimo" },
  { text: "El código es poesía.", author: "WordPress" },
  { text: "Cualquier tonto puede escribir código que una computadora entienda. Un buen programador escribe código que un humano entienda.", author: "Martin Fowler" },
  { text: "Primero, resuelve el problema. Luego, escribe el código.", author: "John Johnson" },
  { text: "La medida del software es que funcione.", author: "Bjarne Stroustrup" },
  { text: "El software está para servir al usuario, no al revés.", author: "Anónimo" },
  { text: "Internet es la primera cosa que la humanidad ha construido y no entiende.", author: "Eric Schmidt" },
  { text: "En internet nadie sabe que eres un perro.", author: "Peter Steiner" },
  { text: "La información es poder.", author: "Francis Bacon" },
  { text: "El saber no ocupa lugar.", author: "Refrán popular" },
  { text: "La inteligencia artificial es el nuevo electricidad.", author: "Andrew Ng" },
  { text: "Los datos son el nuevo petróleo.", author: "Clive Humby" },
  { text: "Sueña en grande, empieza pequeño, actúa ya.", author: "Robin Sharma" },
  { text: "El único límite para nuestra comprensión del mañana serán nuestras dudas de hoy.", author: "Franklin D. Roosevelt" },
  { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
  { text: "No hay nada permanente excepto el cambio.", author: "Heráclito" },
  { text: "Nadie se baña dos veces en el mismo río.", author: "Heráclito" },
  { text: "La curiosidad es el motor de la creatividad.", author: "Arnold Edinborough" }
];
